CREATE TYPE MyInventory_t AS OBJECT(
	name VARCHAR2(100),
	author VARCHAR2(30),
	abstract VARCHAR2(1000)
);

CREATE TYPE MyInventorySet_t AS TABLE OF MyInventory_t;

SELECT
    pc.ENGLISHPRODUCTCATEGORYNAME,
    sum(f.UNITCOST,
    f.UNITSOUT,
    f.UNITSBALANCE
    FROM mydwh.FACTPRODUCTINVENTORY f
         JOIN mydwh.DIMPRODUCT p ON f.PRODUCTKEY = p.PRODUCTKEY
         JOIN MYDWH.DIMPRODUCTSUBCATEGORY psc
             ON p.PRODUCTSUBCATEGORYKEY = psc.PRODUCTSUBCATEGORYKEY
         JOIN MYDWH.DIMPRODUCTCATEGORY pc
             ON psc.PRODUCTCATEGORYKEY = pc.PRODUCTCATEGORYKEY
GROUP BY pc.ENGLISHPRODUCTCATEGORYNAME
ORDER BY pc.ENGLISHPRODUCTCATEGORYNAME;