CREATE OR REPLACE PROCEDURE test_p(p_id INT) IS
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    BEGIN EXECUTE IMMEDIATE 'DROP TABLE TESTS' || p_id; EXCEPTION WHEN OTHERS THEN NULL; END; 
    EXECUTE IMMEDIATE 'CREATE TABLE tests' || p_id || '(tests_id INT, tests varchar2(30))';
END;

BEGIN EXECUTE IMMEDIATE 'DROP TABLE TESTS'; EXCEPTION WHEN OTHERS THEN NULL; END; 
CREATE TABLE tests(tests_id INT, tests_txt varchar2(30));

CREATE OR REPLACE TRIGGER tests_t01
BEFORE INSERT ON tests
FOR EACH ROW
BEGIN
    test_p(:new.tests_id);
END;

INSERT INTO tests VALUES(1, 'a');
INSERT INTO tests VALUES(2, 'b');
ROLLBACK;
